INSERT INTO [dbo].[contact] ([First_Name], [Last_Name], [Password], [Phone_Number], [Email], [Subject], [Message], [Feedback_Rating], [useful_Topic], [Additional_Info_Topic], [Website_Satisfaction], [Admin]) VALUES (N'haim', N'fdsf', N'sdfsdf', N'025136983', N'as@gmail.com', N'asdasd', N'asdasd', 4, N'Starting out', N'Building', 5, NULL)
INSERT INTO [dbo].[contact] ([First_Name], [Last_Name], [Password], [Phone_Number], [Email], [Subject], [Message], [Feedback_Rating], [useful_Topic], [Additional_Info_Topic], [Website_Satisfaction], [Admin]) VALUES (N'dsdf', N'asdasd', N'asdasda', N'0534302017', N'ishitmypants@gmail.com', N'Ssadasd', N'asdasd', 2, N'Building', N'Starting-out', 2, NULL)
INSERT INTO [dbo].[contact] ([First_Name], [Last_Name], [Password], [Phone_Number], [Email], [Subject], [Message], [Feedback_Rating], [useful_Topic], [Additional_Info_Topic], [Website_Satisfaction], [Admin]) VALUES (N'amit', N'maizus', N'Amit123', N'0534302019', N'ami@gmail.com', N'informathion', N'where can I found more informathion about drones?', 4, N'Starting out', N'Building', 5, 1)
INSERT INTO [dbo].[contact] ([First_Name], [Last_Name], [Password], [Phone_Number], [Email], [Subject], [Message], [Feedback_Rating], [useful_Topic], [Additional_Info_Topic], [Website_Satisfaction], [Admin]) VALUES (N'Mosha', N'Cohen', N'Amit123', N'0534304564', N'amitm11@gmail.com', N'asdasd', N'qweasd', 4, N'Betaflight', N'Betaflight', 5, NULL)
INSERT INTO [dbo].[contact] ([First_Name], [Last_Name], [Password], [Phone_Number], [Email], [Subject], [Message], [Feedback_Rating], [useful_Topic], [Additional_Info_Topic], [Website_Satisfaction], [Admin]) VALUES (N'Mosha', N'Cohen', N'amit123', N'0534306593', N'amitm11@gmail.com', N'asdasd', N'asdasd', 3, N'Betaflight', N'Building', 5, NULL)
INSERT INTO [dbo].[contact] ([First_Name], [Last_Name], [Password], [Phone_Number], [Email], [Subject], [Message], [Feedback_Rating], [useful_Topic], [Additional_Info_Topic], [Website_Satisfaction], [Admin]) VALUES (N'Hadas', N'Taba', N'qwe', N'0536892312', N'hadas@taba.com', N'The best website I have ever seen', N'Congratulations! Your work on the website is outstanding. It''s truly the best I''ve ever seen.', 5, N'Betaflight', N'Starting-out,Building', 5, NULL)
INSERT INTO [dbo].[contact] ([First_Name], [Last_Name], [Password], [Phone_Number], [Email], [Subject], [Message], [Feedback_Rating], [useful_Topic], [Additional_Info_Topic], [Website_Satisfaction], [Admin]) VALUES (N'Hadas', N'Taba', N'dsa123', N'0536892360', N'hadas@taba.com', N'The best website I have ever seen', N'Congratulations! Your work on the website is outstanding. It''s truly the best I''ve ever seen. I am impressed by the creativity, functionality, and attention to detail. You''ve set a new standard. Well done!




', 5, N'Betaflight', N'Building,Betaflight', 5, NULL)
INSERT INTO [dbo].[contact] ([First_Name], [Last_Name], [Password], [Phone_Number], [Email], [Subject], [Message], [Feedback_Rating], [useful_Topic], [Additional_Info_Topic], [Website_Satisfaction], [Admin]) VALUES (N'Hadas', N'Taba', N'asdasd', N'0536892369', N'hadas@taba.com', N'The best website I have ever seen', N'aasd', 2, N'Betaflight', N'Building', 4, NULL)
INSERT INTO [dbo].[contact] ([First_Name], [Last_Name], [Password], [Phone_Number], [Email], [Subject], [Message], [Feedback_Rating], [useful_Topic], [Additional_Info_Topic], [Website_Satisfaction], [Admin]) VALUES (N'Amit', N'Taba', N'asd', N'0536892693', N'amit@taba.com', N'Thanks', N'I know', 5, N'Starting-out', N'Building,Betaflight', 5, NULL)
INSERT INTO [dbo].[contact] ([First_Name], [Last_Name], [Password], [Phone_Number], [Email], [Subject], [Message], [Feedback_Rating], [useful_Topic], [Additional_Info_Topic], [Website_Satisfaction], [Admin]) VALUES (N'Mosha', N'Cohen', N'amit123', N'0537892019', N'amitm11@gmail.com', N'asdasd', N'asdasd', 5, N'Building', N'Starting-out', 5, NULL)
INSERT INTO [dbo].[contact] ([First_Name], [Last_Name], [Password], [Phone_Number], [Email], [Subject], [Message], [Feedback_Rating], [useful_Topic], [Additional_Info_Topic], [Website_Satisfaction], [Admin]) VALUES (N'omer', N'asdasd', N'asdasda', N'0547922425', N'omer@gmail.com', N'sad', N'asdad', 2, N'Betaflight', N'Starting-out', 3, NULL)
INSERT INTO [dbo].[contact] ([First_Name], [Last_Name], [Password], [Phone_Number], [Email], [Subject], [Message], [Feedback_Rating], [useful_Topic], [Additional_Info_Topic], [Website_Satisfaction], [Admin]) VALUES (N'asdasd', N'asdasd', N'asdasd', N'0564923620', N'happy@gmail.com', N'asda', N'asdmknji', 3, N'Building', N'Starting-out,Building,Betaflight', 1, NULL)
INSERT INTO [dbo].[contact] ([First_Name], [Last_Name], [Password], [Phone_Number], [Email], [Subject], [Message], [Feedback_Rating], [useful_Topic], [Additional_Info_Topic], [Website_Satisfaction], [Admin]) VALUES (N'amit', N'asd', N'asd', N'056923459', N'asda@gmail.com', N'asda', N'sdasd', 3, N'Starting out', N'Building', 4, NULL)
INSERT INTO [dbo].[contact] ([First_Name], [Last_Name], [Password], [Phone_Number], [Email], [Subject], [Message], [Feedback_Rating], [useful_Topic], [Additional_Info_Topic], [Website_Satisfaction], [Admin]) VALUES (N'amit', N'asd', N'asd', N'0569459589', N'asdasaa@gmail.com', N'asas', N'asasa', 3, N'Starting out', N'Building', 4, NULL)
INSERT INTO [dbo].[contact] ([First_Name], [Last_Name], [Password], [Phone_Number], [Email], [Subject], [Message], [Feedback_Rating], [useful_Topic], [Additional_Info_Topic], [Website_Satisfaction], [Admin]) VALUES (N'Mosha', N'Cohen', N'Amit123', N'1234567890', N'amitm11@gmail.com', N'asdasd', N'asdasd', 2, N'Betaflight', N'Building', 5, NULL)
